### ISSUE TITLE
what about  mysql oracle

### ISSUE THREAD

**Issue by wanghaisheng** [subzerocloud/subzero-starter-kit#2]
https://github.com/atulmy/fullstack-graphql
here  it use Sequelize  to adapt all kinds  of ER database, any thoughts

**Comment by ruslantalpa** [comment]
mysql/oracle miss features (last time i checked) to allow a stack similar to postgrest+postgresql. maybe in the future.
The thing you linked to is just traditional way of building apis (you write all the imperative code), nothing new, and i have not seen there the most interesting thing about graphql, embedding related entities

**Comment by wanghaisheng** [comment]
is there any trick way to deal with mysql or oracle  such as  streaming change data from source mysql/oracle  into postgresql ?

**Comment by ruslantalpa** [comment]
although not ideal, you could somehow use FDWs to make the remote tables available in postgresql and then based on them, create materialised views and periodically update them. though i would go for this only in extreme cases where there is no way to migrate to postgresql because the old database is used by some other software.
in short, there are ways, but the implementation would be very specific to your use case
