### ISSUE TITLE
tutorial -> GraphQL example

### ISSUE THREAD

**Issue by FabienD** [subzerocloud/subzero-starter-kit#7]
Hi,

Thank you for your project, I played a little with it, it's really cool !!!
I've one question about GraphQL example in the tutorial, I've an error when I try this query : 

```
{
  projects(where: {name: {ilike: "*3*"}}) {
    id
    name
    tasks(where: {completed: {eq: false}}){
      id
      name
    }
  }
}
```

Here is the error :

```

  "data": {
    "projects": null
  },
  "errors": [
    {
      "hint": null,
      "details": null,
      "code": "42703",
      "message": "column projects.tasks does not exist"
    }
  ]
}
```

Getting objects with relationships across views should work?

Thanks you,
Fabien

**Comment by ruslantalpa** [comment]
yes, should work, when you edit your sql files, you need to have subzero watch/dashboard running in order to pick your changes and load them in the db and restart the apropriate containers.
try doing a docker-compose down/up

**Comment by FabienD** [comment]
Hi,

I'll **retry the tutorial from the beginning**, restart containers doesn't fix the issue.

Thanks

**Comment by davidknaack** [comment]
I'm experiencing this too. I've restarted containers and double-checked that the SQL I've added as part of the tutorial is copied correctly. I've tried to confirm via pgAdmin that the database schema appears to be correct, with the appropriate foreign key references.

Seems like an issue somewhere in the customized parts subzerocloud/openresty container, but I was not able to find any sources, so I was not able to investigate more deeply (startup secrets I presume 👍).

Below are the queries and results I'm trying along with the results I get when I try the equivalent query with PostgREST. Maybe these will help to find the problem.

This GraphiQL query:
```
{
  projects {
    id
    name
  }
}
```

Produces the expected result:
```
{
  "data": {
    "projects": [
      {
        "id": 1,
        "name": "MacOS"
      },
      {
        "id": 2,
        "name": "Windows"
      },
      {
        "id": 3,
        "name": "IOS"
      },
      {
        "id": 4,
        "name": "Office"
      }
    ]
  }
}
```

And the equivalent PostgREST curl query also works:
```
curl -s -H "Authorization: Bearer $JWT_TOKEN" 'http://localhost:8080/rest/projects?select=id,name'
```

producing:
```
[
  {
    "id": 1,
    "name": "MacOS"
  },
  {
    "id": 2,
    "name": "Windows"
  },
  {
    "id": 3,
    "name": "IOS"
  },
  {
    "id": 4,
    "name": "Office"
  }
]
```

But the GraphiQL query:
```
{
  projects {
    id
    name
    tasks {
      id
    }
  }
}
```

fails, producing:
```
{
  "data": {
    "clients": null
  },
  "errors": [
    {
      "hint": null,
      "details": null,
      "code": "42703",
      "message": "column clients.projects does not exist"
    }
  ]
}
```

while the equivalent PostgREST curl query:
```
curl -s -H "Authorization: Bearer $JWT_TOKEN" 'http://localhost:8080/rest/projects?select=id,name,tasks(id)'
```

works, producing:
```
[
  {
    "id": 1,
    "name": "MacOS",
    "tasks": [
      {
        "id": 1
      },
      {
        "id": 2
      }
    ]
  },
  {
    "id": 2,
    "name": "Windows",
    "tasks": [
      {
        "id": 3
      }
    ]
  },
  {
    "id": 3,
    "name": "IOS",
    "tasks": [
      {
        "id": 4
      }
    ]
  },
  {
    "id": 4,
    "name": "Office",
    "tasks": [
      {
        "id": 5
      }
    ]
  }
]
```

If I modify the PostgREST query to remove the '(id)' part:
```
curl -H "Authorization: Bearer $JWT_TOKEN" 'http://localhost:8080/rest/projects?select=id,name,tasks'
```

or the 'id' field:
```
curl -H "Authorization: Bearer $JWT_TOKEN" 'http://localhost:8080/rest/projects?select=id,name,tasks()'
```

then it produces the same error as GraphiQL:
```
{
  "hint": null,
  "details": null,
  "code": "42703",
  "message": "column projects.tasks does not exist"
}
```

There are also other odd results. For example GraphiQL:
```
{
  projects(limit:1) {
    id
    name
    client {
      id
      name
    }
  }
}
```

produces:
```
{
  "data": {
    "projects": [
      {
        "id": 1,
        "name": "MacOS",
        "client": 1
      }
    ]
  }
}
```
when it should be producing something more like:
```
curl -s -H "Authorization: Bearer $JWT_TOKEN" 'http://localhost:8080/rest/projects?select=id,name,client(id,name)&limit=1'
```
```
[
  {
    "id": 1,
    "name": "MacOS",
    "client": {
      "id": 1,
      "name": "Apple"
    }
  }
]
```

And
```
{
  projects(limit:1) {
    id
    name
    client {
      id
      name
    }
    tasks {
      id
    }
  }
}
```
seems to ignore the 'tasks' part, producing:
```
{
  "data": {
    "projects": [
      {
        "id": 1,
        "name": "MacOS",
        "client": 1
      }
    ]
  }
}
```

while reversing the order of 'client' and 'tasks':
```
{
  projects(limit:1) {
    id
    name
    tasks {
      id
    }
    client {
      id
      name
    }
  }
}
```

brings back the error message:
```
{
  "data": {
    "projects": null
  },
  "errors": [
    {
      "hint": null,
      "details": null,
      "code": "42703",
      "message": "column projects.tasks does not exist"
    }
  ]
}
```

In each example the equivalent PostgREST query produces the expected results.

Querying the /graphql/simple endpoint rather than using the GraphiQL IDE does not change the GraphiQL results, so the problem doesn't seem to be anything related to the IDE.

**Comment by ruslantalpa** [comment]
thank you for the detailed report and specific query/output reports. I'll look into them this week and get back

**Comment by ruslantalpa** [comment]
this has been fixed
try refreshing docker images
```
docker-compose down
docker pull subzerocloud/openresty
docker pull subzerocloud/postgrest
docker-compose up -d
```
